### ISSUE TITLE
Colorchoices is now part of netbox class instead of utilities, having this script breaks update to 4.0.x

### ISSUE THREAD

**Issue by aseques** [netbox-community/customizations#105]
We had this script on the scripts folder, when we upgraded to 4.0.1 the update process broke because the dependency on ColorChoices can no longer be satisfied.

https://github.com/netbox-community/customizations/blob/4debbb49fc7e541b4bf0f6f5e43aee4a8255754f/scripts/multi_connect.py#L13

**Comment by candlerb** [comment]
See #106, #107

**Comment by jsenecal** [comment]
Fixed in #107
