### ISSUE TITLE
multi_connect.py not executable in version 4.0.10

### ISSUE THREAD

**Issue by crusaderflex** [netbox-community/customizations#110]
After updating from 3.7.8 to 4.0.10 multi_connect.py could not executed.
I delete and upload script, which has no change.
Also i could not edit the script from the GUI, other scripts work well.
 
![2024-09-16 08_22_56-](https://github.com/user-attachments/assets/e9d0a7c4-ef26-46d5-a084-8d04795964be)

Greets Michael

**Comment by jsenecal** [comment]
#107 was merged few minutes ago, can you try again and confirm if this is now fixed ?

**Comment by crusaderflex** [comment]
Works perfectly, thanks for the quick troubleshooting. 

Greetings Michael
