### ISSUE TITLE
FR: Add export templates and change name

### ISSUE THREAD

**Issue by martinum4** [netbox-community/customizations#61]
Hello,

so far this repository collects reports and scripts, thus the name seems already a bit misleading.
I propose that this repository should be renamed (maybe something like "user_generated_content") and the ability to add export templates is added.
Benefit: Users are encouraged to submit their templates, we all can learn a bit from it or get new ideas.

**Comment by ryanmerolle** [comment]
I like this idea.  Sorry for the delay.  I will discuss with the team.

**Comment by martinum4** [comment]
I noticed the repository name was changed, however seems to take care of the pull requests in this repo, maybe automate this task?
